FROM node:latest
# Working tree
WORKDIR /app

# copying package.json file
COPY ["package.json" , "package-lock.json","./"]

# installing packages
RUN npm install -y

# copying current working directory to the container
# copying file system to working directory
COPY . .

# compiling packages
RUN npm run compile

# EXPOSE 4040
# Attaching volume
VOLUME ["/home/emmanuel/app" , "/app"]
# running main server
CMD [ "node"  , "./main/server.js" ]
